# Generated by Django 6.0.6 on 2026-06-14 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_food_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='rating',
            field=models.IntegerField(choices=[(1, '★☆☆☆☆'), (2, '★★☆☆☆'), (3, '★★★☆☆'), (4, '★★★★☆'), (5, '★★★★★')], default=4),
        ),
    ]
