# Generated by Django 6.0.6 on 2026-06-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_food_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='location',
            field=models.CharField(choices=[('Agrabad', 'Agrabad'), ('GEC Circle', 'GEC Circle'), ('Halishahar', 'Halishahar'), ('Kotwali', 'Kotwali'), ('Panchlaish', 'Panchlaish')], default='Agrabad', max_length=50),
        ),
    ]
