# Generated by Django 6.0.6 on 2026-06-14 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_food_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='location',
        ),
    ]
